apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-microservice
  labels:
    app: devops-microservice
spec:
  replicas: 2  # ← 2 PODS como solicitas
  selector:
    matchLabels:
      app: devops-microservice
  template:
    metadata:
      labels:
        app: devops-microservice
    spec:
      containers:
        - name: microservice
          image: 730335561060.dkr.ecr.us-east-1.amazonaws.com/devops-microservice:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"

