name: DevOps Microservice CI/CD

on:
  push:
    branches: [ master ]  # ← CAMBIADO de main a master
  pull_request:
    branches: [ master ]  # ← CAMBIADO de main a master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn test

      - name: Build application
        run: mvn clean compile

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # ← CAMBIADO de main a master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t devops-microservice:latest .